language: node_js
node_js:
  - "stable"
cache:
  directories:
  - node_modules
script:
  - react-scripts build

deploy:
  provider: pages
  skip-cleanup: true
  local-dir: build
  target-branch: output
  github-token: $GH_TOKEN
  keep-history: true
  on:
    branch: master

before_script:
  - sudo chown -v $USER ~/.ssh/known_hosts

after_script:
  - git init
  - git config user.name "neteraxe"
  - git config user.email "neteraxe@126.com"
  - git add .
  - git commit -m "Travis-CL automate deploy"
  # Coding Pages
  - git push --force "${CO_TOKEN}@${CO_REF}" master:master

env:
 global:
   # Coding Pages
   - CO_REF: git@e.coding.net:neteraxe/neteraxe/neteraxe.git