language: node_js
node_js:
  - "stable"
cache:
  directories:
  - node_modules
script:
  - react-scripts build
deploy:
  provider: pages
  skip_cleanup: true
  github_token: 6f83beb2fa12ea53de9af4ba05d52a95ec4b17fa
  local_dir: build
  target-branch: master
  on:
    branch: gh-pages