language: node_js
node_js:
  - "stable"
cache:
  directories:
  - node_modules
script:
  - react-scripts build

after_script:
  - git init
  - git config user.name "neteraxe"
  - git config user.email "neteraxe@126.com"
  - git add .
  - git commit -m "Update Blog By TravisCI With Build $TRAVIS_BUILD_NUMBER"
  # Github Pages
  - git push --force --quiet "https://${GH_TOKEN}@${GH_REF}" master:master 
  # Coding Pages
  - git push --force --quiet "https://neteraxe:${CO_TOKEN}@${CO_REF}" master:master
  - git tag v0.0.$TRAVIS_BUILD_NUMBER -a -m "Auto Taged By TravisCI With Build $TRAVIS_BUILD_NUMBER"
  # Github Pages
  - git push --quiet "https://${GH_TOKEN}@${GH_REF}" master:master --tags
  # Coding Pages
  - git push --quiet "https://neteraxe:${CO_TOKEN}@${CO_REF}" master:master --tags

branches:
  only:
    - output

env:
 global:
 # Github Pages
   - GH_REF: https://github.com/Neteraxe/react-material-ui-markdown-blog
   # Coding Pages
   - CO_REF: git@e.coding.net:neteraxe/neteraxe/neteraxe.git