language: node_js
node_js:
  - "stable"
cache:
  directories:
  - node_modules
script:
  - react-scripts build
deploy:
  provider: pages
  skip_cleanup: true
  github_token: efcf72d9076b24d698ecd59ba04b86be7d6fc398
  local_dir: build
  target_branch: gh-pages
  on:
    branch: master