language: node_js
node_js:
  - "stable"
cache:
  directories:
  - node_modules
script:
  - react-scripts build
deploy:
  provider: pages
  skip_cleanup: true
  github_token: 62fca555ae0f42b29dbdf11c21c129b95398848a
  local_dir: build
  target_branch: gh-pages
  on:
    branch: master