language: node_js
node_js:
  - "stable"
cache:
  directories:
  - node_modules
script:
  - react-scripts build

deploy:
  target_branch: gh-pages
  on:
      branch: master 
  - git init
  - git config user.name "neteraxe"
  - git config user.email "neteraxe@126.com"
  - git add .
  - git commit -m "Travis-CL automate deploy"
  # Github Pages
  - git push --force "https://${GH_TOKEN}@${GH_REF}" master:master 
  # Coding Pages
  - git push --force "https://neteraxe:${CO_TOKEN}@${CO_REF}" master:master

branches:

env:
 global:
 # Github Pages
   - GH_REF: https://github.com/Neteraxe/react-material-ui-markdown-blog
   # Coding Pages
   - CO_REF: git@e.coding.net:neteraxe/neteraxe/neteraxe.git