language: node_js
node_js:
  - "stable"
cache:
  directories:
  - node_modules
script:
  - react-scripts build
deploy:
  provider: pages
  skip_cleanup: true
  github_token: 3aca07be1e64d7cdb117b6f725070c8cc2a2be28
  local_dir: build
  target-branch: gh-pages
  on:
    branch: master
